name: 习讯云自动签到

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *  # 每天UTC 0点（carlifornia）
    - cron: 0 12 * * * # 每天UTC 12点

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 使用 Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: 安装依赖
        run: npm install
      - name: 签到日志
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ADDRESS: ${{ secrets.ADDRESS }}
          ADDRESS_NAME: ${{ secrets.ADDRESS_NAME }}
          LATITUDE: ${{ secrets.LATITUDE }}
          LONGITUDE: ${{ secrets.LONGITUDE }}
          SCHOOL_ID: ${{ secrets.SCHOOL_ID }}
          EMAIL: ${{ secrets.EMAIL }}
          CODE: ${{ secrets.CODE }}
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          node app.js
