name: 自动签到

on:
  schedule:
    - cron: '0 0,12 * * *' # 每天UTC 0点和12点触发

jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v2

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v2
        with:
          node-version: 10.x

      - name: 安装依赖并签到
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ADDRESS: ${{ secrets.ADDRESS }}
          ADDRESS_NAME: ${{ secrets.ADDRESS_NAME }}
          LATITUDE: ${{ secrets.LATITUDE }}
          LONGITUDE: ${{ secrets.LONGITUDE }}
          SCHOOL_ID: ${{ secrets.SCHOOL_ID }}
          EMAIL: ${{ secrets.EMAIL }}
          CODE: ${{ secrets.CODE }}
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          npm ci --silent
          node app.js > sign_log.txt 2>&1 || echo "签到失败，请检查日志"
